--- #YAML:1.0
name:               Geo-Coder-Mapquest
version:            0.01
abstract:           Geocode addresses with Mapquest (beta)
author:
    - gray <gray@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    JSON:            2
    LWP::UserAgent:  0
    Test::More:      0
    URI:             1.36
resources:
    repository:  http://github.com/gray/geo-coder-mapquest
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    JSON::XS:  2
